from pathlib import Path

p = Path("tools/hardening_migrate.py")
text = p.read_text()

# Preserve escaped quotes in the Rust source generated by the Python migration.
old_escape = r'    "extern \"C\"",'
new_escape = r'    "extern \\\"C\\\"",'
if old_escape in text:
    text = text.replace(old_escape, new_escape, 1)
elif new_escape not in text:
    raise SystemExit("migration escape pattern not found")

# The registry warning was already fixed directly on the branch. Remove that
# one-shot replacement so the remaining migration stays applicable.
registry_block = '''# Registry warning.
replace(
    "forge-core/src/registry.rs",
    "Ok((key, ivec)) if key.as_ref().starts_with(SYSTEM_PREFIX) => None,",
    "Ok((key, _ivec)) if key.as_ref().starts_with(SYSTEM_PREFIX) => None,",
)

'''
if registry_block in text:
    text = text.replace(registry_block, "# Registry warning already migrated.\n\n", 1)

p.write_text(text)
